'use strict';

module.exports = 
{ "Maccabi Haifa": 0.3, 
    "Beitar Jerusalem": 0.3, 
    "Hapoel Tel Aviv": 0.3, 
    "SC Ashdod": 0.2, 
    "Hapoel Beer Sheva": 0.3, 
    "Hapoel Kfar Saba": 0.2, 
    "Hapoel Haifa": 0.2, 
    "Bnie Sakhnin": 0.2, 
    "Hapoel Akko": 0.2, 
    "Maccabi Natanya": 0.2, 
    "Hapoel Petah Tikva": 0.2, 
    "Maccabi Petah Tikva": 0.2, 
    "Viktoria Köln": 0.25,
    "Rot-Weiss Essen": 0.25,
    "Jahn Regensburg": 0.25,
    "Wattenscheid 09": 0.25,
    "FC Astoria Walldorf": 0.25,
    "Bremer SV": 0.25,
    "Eintracht Norderstedt": 0.25,
    "Germania Egestorf": 0.25,
    "SC Hauenstein": 0.25,
    "Sportfreunde Lotte": 0.25,
    "SpVgg Unterhaching": 0.25,
    "Homburg": 0.25,
    "SV Babelsberg 03": 0.25,
    "FSV Zwickau": 0.25,
    "FC 08 Villingen": 0.25,
    "SV Drochtersen/Assel": 0.25,
    "BFC Preussen": 0.25,
    "Kickers Offenbach": 0.25,
    "FV Ravensburg": 0.25,
    "FC Carl Zeiss Jena": 0.25,
    "VfB Lübeck": 0.25,
    "Eintracht Trier": 0.25,
    "Athletic Bilbao B": 0.3,
    "Albacete Balompié": 0.3,
    "UE Llagostera": 0.3,
    "SD Ponferradina": 0.3,
    "FSV Frankfurt": 0.35,
    "Karlsruher SC": 0.35,
    "SC Paderborn 07": 0.35,
    "1. FC Kaiserslautern": 0.5,
    "Arminia Bielefeld": 0.5,
    "MSV Duisburg": 0.5,
    "VfL Bochum": 0.5,
    "1. FC Union Berlin": 0.35,
    "1. FC Nürnberg": 0.35,
    "Eintracht Braunschweig": 0.35,
    "SpVgg Greuther Fürth": 0.35,
    "TSV 1860 München": 0.35,
    "1. FC Heidenheim 1846": 0.35,
    "SV Sandhausen": 0.35,
    "Fortuna Düsseldorf": 0.35,
    "FC St. Pauli": 0.35,
    "Amiens SC": 0.45,
    "AJ Auxerre": 0.45,
    "Red Star 93": 0.45,
    "Sochaux FC": 0.45,
    "Real Oviedo": 0.45,
    "Ajaccio AC": 0.45,
    "US Créteil": 0.45,
    "Évian Thonon Gaillard FC": 0.45,
    "RC Tours": 0.45,
    "Paris FC": 0.45,
    "Clermont Foot Auvergne": 0.45,
    "FC Valenciennes": 0.45,
    "Le Havre AC": 0.45,
    "US Orleans": 0.45,
    "RC Lens": 0.45,
    "Chamois Niortais FC": 0.45,
    "FC Stade Lavallois Mayenne": 0.45,
    "Nîmes Olympique": 0.45,
    "Stade Brestois": 0.45,
    "Strasbourg": 0.45,
    "FC Bourg-en-Bresse Péronnas": 0.45,
    "UCAM Murcia": 0.45,
    "Real Zaragoza": 0.45,
    "Real Valladolid": 0.45,
    "Girona FC": 0.45,
    "Sevilla II": 0.45,
    "CD Lugo": 0.45,
    "Gimnàstic de Tarragona": 0.45,
    "CD Numancia de Soria": 0.45,
    "CD Tenerife": 0.45,
    "Córdoba CF": 0.45,
    "CF Reus Deportiu": 0.45,
    "RCD Mallorca": 0.45,
    "Elche FC": 0.45,
    "Huesca": 0.45,
    "AD Alcorcón": 0.45,
    "Cádiz CF": 0.45,
    "UD Almeria": 0.45,
    "CD Mirandes": 0.45,
    "Colchester United FC": 0.5,
    "Crewe Alexandra FC": 0.5,
    "Bolton Wanderers FC": 0.55,
    "Sheffield United FC": 0.5,
    "Scunthorpe United FC": 0.5,
    "Bristol Rovers": 0.5,
    "Oxford United": 0.4,
    "Dynamo Dresden": 0.35,
    "Chesterfield FC": 0.4,
    "Northampton Town": 0.4,
    "Würzburger Kickers": 0.3,
    "Fleetwood Town FC": 0.4,
    "Bury FC": 0.3,
    "Charlton Athletic": 0.3,
    "Erzgebirge Aue": 0.3,
    "Swindon Town FC": 0.5,
    "Coventry City FC": 0.5,
    "Southend United FC": 0.5,
    "Gillingham FC": 0.5,
    "Shrewsbury Town FC": 0.4,
    "Milton Keynes Dons": 0.5,
    "Rochdale AFC": 0.4,
    "Peterborough United FC": 0.5,
    "Millwall FC": 0.5,
    "Oldham Athletic AFC": 0.4,
    "Bradford City AFC": 0.4,
    "Port Vale FC": 0.4,
    "Walsall FC": 0.4,
    "AFC Wimbledon": 0.4,
    "Doncaster Rovers FC": 0.5,
    "Hallescher FC": 0.3,
    "Energie Cottbus": 0.5,
    "Chemnitzer FC": 0.3,
    "VfR Aalen": 0.3,
    "VfB Stuttgart II": 0.3,
    "VfL Osnabrück": 0.3,
    "Mainz 05 II": 0.3,
    "Holstein Kiel": 0.3,
    "1. FC Magdeburg": 0.3,
    "SG Sonnenhof Großaspach": 0.3,
    "Preußen Münster": 0.3,
    "Fortuna Köln": 0.3,
    "Stuttgarter Kickers": 0.3,
    "Werder Bremen II": 0.3,
    "SV Wehen Wiesbaden": 0.3,
    "Rot-Weiß Erfurt": 0.3,
    "Blackpool FC": 0.5,
    "FC Hansa Rostock": 0.5,
    "Rotherham United": 0.55,
    "Barnsley FC": 0.55,
    "Cardiff City FC": 0.6,
    "Bristol City": 0.6,
    "Wigan Athletic FC": 0.6,
    "Derby County": 0.5,
    "Brighton": 0.65,
    "Queens Park Rangers": 0.65,
    "Leeds United": 0.6,
    "Sheffield Wednesday": 0.6,
    "G.D. Chaves": 0.4,
    "Ipswich Town": 0.6,
    "Feirense": 0.4,
    "Burton Albion FC": 0.5,
    "Nottingham Forest": 0.6,
    "Preston North End": 0.6,
    "Reading": 0.6,
    "Wolverhampton Wanderers FC": 0.6,
    "Académica de Coimbra": 0.4,
    "Birmingham City": 0.6,
    "FC Paços de Ferreira": 0.4,
    "Blackburn Rovers FC": 0.6,
    "GD Estoril Praia": 0.4,
    "Fulham FC": 0.6,
    "Nacional Funchal": 0.45,
    "Sporting Braga": 0.55,
    "FC Arouca": 0.4,
    "Moreirense FC": 0.4,
    "Maritimo Funchal": 0.45,
    "União Madeira": 0.4,
    "Boavista": 0.5,
    "Vitoria Setubal": 0.4,
    "Vitoria Guimaraes": 0.4,
    "FC Rio Ave": 0.4,
    "C.F. Os Belenenses": 0.4,
    "CD Tondela": 0.4,
    "Huddersfield Town": 0.5,
    "Brentford FC": 0.5,
    "FC Utrecht": 0.55,
    "Excelsior": 0.55,
    "FC Twente Enschede": 0.6,
    "Go Ahead Eagles Deventer": 0.55,
    "ADO Den Haag": 0.55,
    "PEC Zwolle": 0.55,
    "NEC Nijmegen": 0.55,
    "Heracles Almelo": 0.55,
    "Roda JC Kerkrade": 0.55,
    "ES Troyes AC": 0.5,
    "Ajax Amsterdam": 0.8,
    "Sparta Rotterdam": 0.55,
    "SC Heerenveen": 0.6,
    "Stade de Reims": 0.6,
    "OSC Lille": 0.7,
    "AZ Alkmaar": 0.7,
    "Feyenoord Rotterdam": 0.7,
    "FC Groningen": 0.6,
    "Vitesse Arnhem": 0.65,
    "SC Cambuur-Leeuwarden": 0.5,
    "De Graafschap": 0.5,
    "Gazélec Ajaccio": 0.6,
    "Toulouse FC": 0.65,
    "Olympique de Marseille": 0.8,
    "Stade Rennais FC": 0.65,
    "OGC Nice": 0.65,
    "SC Bastia": 0.6,
    "EA Guingamp": 0.65,
    "FC Girondins de Bordeaux": 0.7,
    "AS Saint-Étienne": 0.65,
    "SM Caen": 0.6,
    "FC Lorient": 0.6,
    "Dijon FCO": 0.6,
    "FC Nantes": 0.6,
    "FC Metz": 0.6,
    "Willem II Tilburg": 0.6,
    "Montpellier Hérault SC": 0.55,
    "Angers SCO": 0.55,
    "AS Nancy": 0.6,
    "Genoa CFC": 0.6,
    "SD Eibar": 0.6,
    "Villarreal CF": 0.7,
    "Real Betis": 0.7,
    "RC Celta de Vigo": 0.7,
    "CA Osasuna": 0.5,
    "Deportivo Alavés": 0.6,
    "CD Leganes": 0.6,
    "Sporting Gijón": 0.65,
    "Athletic Club": 0.7,
    "Hellas Verona FC": 0.6,
    "Carpi FC": 0.6,
    "Frosinone Calcio": 0.75,
    "Málaga CF": 0.75,
    "UD Las Palmas": 0.65,
    "RCD Espanyol": 0.75,
    "Real Sociedad de Fútbol": 0.7,
    "RC Deportivo La Coruna": 0.65,
    "Pescara Calcio": 0.7,
    "Atalanta BC": 0.7,
    "SS Lazio": 0.75,
    "Hannover 96": 0.7,
    "VfB Stuttgart": 0.75,
    "Werder Bremen": 0.75,
    "Levante UD": 0.65,
    "Newcastle United FC": 0.8,
    "Norwich City FC": 0.75,
    "Rayo Vallecano de Madrid": 0.65,
    "US Sassuolo Calcio": 0.7,
    "US Cittá di Palermo": 0.75,
    "FC Crotone": 0.65,
    "Bologna FC": 0.75,
    "Getafe CF": 0.75,
    "Aston Villa FC": 0.75,
    "Cagliari Calcio": 0.7,
    "Granada CF": 0.7,
    "UC Sampdoria": 0.7,
    "Empoli FC": 0.7,
    "FC Internazionale Milano": 0.85,
    "AC Chievo Verona": 0.7,
    "Torino FC": 0.75,
    "AC Milan": 0.85,
    "ACF Fiorentina": 0.75,
    "Udinese Calcio": 0.75,
    "West Ham United FC": 0.8,
    "Liverpool FC": 0.9,
    "AFC Bournemouth": 0.75,
    "Sunderland AFC": 0.75,
    "Swansea City FC": 0.8,
    "Burnley FC": 0.75,
    "West Bromwich Albion FC": 0.8,
    "Crystal Palace FC": 0.8,
    "Everton FC": 0.8,
    "Stoke City FC": 0.8,
    "Middlesbrough FC": 0.8,
    "Watford FC": 0.8,
    "Southampton FC": 0.8,
    "Hull City FC": 0.8,
    "Red Bull Leipzig": 0.75,
    "TSG 1899 Hoffenheim": 0.75,
    "SC Freiburg": 0.75,
    "Hertha BSC": 0.75,
    "SV Darmstadt 98": 0.75,
    "1. FC Köln": 0.75,
    "FC Ingolstadt 04": 0.75,
    "Hamburger SV": 0.75,
    "FC Schalke 04": 0.75,
    "Eintracht Frankfurt": 0.6,
    "1. FSV Mainz 05": 0.6,
    "FC Augsburg": 0.6,
    "Shakhtar Donetsk": 0.7,
    "FC Zenit St. Petersburg": 0.7,
    "Maccabi Tel Aviv": 0.6,
    "Olympiacos F.C.": 0.5,
    "FK BATE Baryssau": 0.5,
    "KAA Gent": 0.5,
    "Juventus": 0.9,
    "Olympique Lyonnais": 0.8,
    "AS Roma": 0.8,
    "SSC Napoli": 0.8,
    "Chelsea FC": 1,
    "Valencia CF": 0.8,
    "Arsenal FC": 1,
    "Manchester United FC": 1,
    "FC Bayern München": 1,
    "Sevilla FC": 0.9,
    "Manchester City FC": 0.9,
    "FC Basel": 0.55,
    "Ludogorez Rasgrad": 0.5,
    "FC Rostov": 0.5,
    "Celtic FC": 0.7,
    "Tottenham Hotspur FC": 0.9,
    "PSV Eindhoven": 0.7,
    "SL Benfica": 0.7,
    "Besiktas JK": 0.7,
    "Legia Warszawa": 0.5,
    "GNK Dinamo Zagreb": 0.5,
    "Leicester City FC": 0.8,
    "FC Porto": 0.75,
    "FC Copenhagen": 0.6,
    "Club Brugge": 0.6,
    "Sporting CP": 0.7,
    "CSKA Moscow": 0.6,
    "Bayer Leverkusen": 0.85,
    "Bor. Mönchengladbach": 0.8,
    "FC Barcelona": 1,
    "Paris Saint-Germain": 0.85,
    "AS Monaco FC": 0.7,
    "Club Atlético de Madrid": 0.85,
    "Real Madrid CF": 1,
    "Malmö FF": 0.5,
    "FC Astana": 0.5,
    "Borussia Dortmund": 0.85,
    "VfL Wolfsburg": 0.8,
    "Galatasaray SK": 0.6,
    "Dynamo Kyiv": 0.6
};