var pages = [
	'FC Bazenheid',
	'FC Wil',
	'FC Luzern',
	'BSC Young Boys',
	'Fulham F.C.',
	'FC Sion',
	'Guardia Republicana',
	'Coronel Bolognesi',
	'Sport Agustino',
	'FBC Melgar',
	'Coventry City F.C.',
	'Estudiantes de La Plata',
	'Cruz Azul Hidalgo',
	'Universitario de Deportes',
	'Atlético Universidad',
	'Sporting Cristal',
	'Bursaspor',
	'Juan Aurich',
	'Feyenoord',
	'RKC Waalwijk',
	'SC Heerenveen',
	'West Bromwich Albion F.C.',
	'Ipswich Town F.C.',
	'RCD Mallorca',
	'ADO Den Haag',
	'SM Caen',
	'Olympique Marseille',
	'Wolverhampton Wanderers F.C.',
	'AC Ajaccio',
	'New York Red Bulls',
	'New York Red Bulls II',
	'AS Saint-Étienne',
	'Chelsea F.C.',
	'U.S.D. Nuorese Calcio',
	'A.S.D. S.E.F. Torres 1903',
	'S.S.C. Napoli',
	'Parma F.C.',
	'Cagliari Calcio',
	'ASEC Mimosas',
	'K.R.C. Genk',
	'Tottenham Hotspur F.C.',
	'Sevilla FC',
	'Trabzonspor',
	'Akhisar Belediyespor',
	'FC Pune City',
	'Maccabi Jaffa F.C.',
	'Maccabi Tel Aviv F.C.',
	'Royal Antwerp FC',
	'Beitar Jerusalem F.C.',
	'Crystal Palace F.C.',
	'Maccabi Haifa F.C.',
	'Maccabi Herzliya F.C.',
	'Maccabi Netanya F.C.',
	'F.C. Ashdod',
	'Hapoel Nazareth Illit F.C.',
	'NK Marsonia',
	'NK Hrvatski Dragovoljac',
	'Bayer 04 Leverkusen',
	'Portsmouth F.C.',
	'VfB Stuttgart',
	'1. FC Köln',
	'HNK Hajduk Split',
	'AIK Bačka Topola',
	'FK Mornar',
	'FK Kolubara',
	'Red Star Belgrade',
	'FK Spartak Subotica',
	'Racing de Santander',
	'Valencia CF',
	'Birmingham City F.C.',
	'FC Bayern Munich',
	'A.C. Milan',
	'Middlesbrough F.C.',
	'Liverpool F.C.',
	'Borussia Mönchengladbach',
	'FC Spartak Tambov',
	'PFC CSKA Moscow',
	'FC Anzhi Makhachkala',
	'FC Dynamo Moscow',
	'FC Zenit Saint Petersburg',
	'Shenzhen Ruby F.C.',
	'Shandong Luneng Taishan F.C.',
	'Charlton Athletic F.C.',
	'Celtic F.C.',
	'Guangzhou Evergrande F.C.',
	'P.A.O.K. F.C.',
	'Levante UD',
	'UD Las Palmas',
	'PSV Eindhoven',
	'FC Barcelona',
	'Olympique de Marseille',
	'Sunderland A.F.C',
	'Sydney United FC',
	'Sydney Olympic',
	'Borussia Dortmund',
	'Queens Park Rangers F.C.',
	'Eintracht Frankfurt',
	'AJ Auxerre',
	'1860 München',
	'Kyoto Sanga F.C.',
	'Urawa Red Diamonds',
	'Wacker Innsbruck',
	'Newcastle Jets',
	'Helmond Sport',
	'FC Dinamo Tbilisi',
	'RC Lens',
	'Hull City A.F.C.',
	'Konyaspor',
	'İstanbul Büyükşehir Belediyespor (football team)',
	'Sheffield Wednesday F.C.',
	'Al Raed',
	'Unión de Santa Fe',
	'RC Strasbourg',
	'Troyes AC',
	'Derby County F.C.',
	'A.C. Ancona',
	'Calcio Catania',
	'Ionikos F.C.',
	'Pisa Calcio',
	'Torino F.C.',
	'Club Atlético Vélez Sarsfield',
	'Al Sadd SC',
	'S.S. Lazio',
	'Inter Milan',
	'West Ham United F.C.',
	'ACF Fiorentina',
	'Bristol Rovers F.C.',
	'Bath City F.C.',
	'Brighton & Hove Albion F.C.',
	'El Mansoura SC',
	'ENPPI Club',
	'FC Lokomotiv Moscow',
	'Zamalek SC',
	'Wigan Athletic F.C.',
	'Elazığspor',
	'Al-Salmiya SC',
	'Raja Casablanca',
	'Al Ahed',
	'El Mokawloon SC',
	'Manchester United F.C.',
	'Cardiff City F.C.',
	'Kavala F.C.',
	'PAOK FC',
	'Leicester City F.C.',
	'AEK Athens F.C.',
	'Bologna F.C. 1909',
	'Club Atlético San Lorenzo de Almagro',
	'RCD Espanyol',
	'Manchester City F.C.',
	'Jeonnam Dragons',
	'Doncaster Rovers F.C.',
	'Aston Villa F.C.',
	'Southall F.C.',
	'Slough Town F.C.',
	'Wimbledon F.C.',
	'Enfield F.C.',
	'Egham Town F.C.',
	'Watford F.C.',
	'Everton F.C.',
	'Wrexham F.C.',
	'Bradford City A.F.C.',
	'Huddersfield Town F.C.',
	'Grays Athletic F.C.',
	'Nagoya Grampus',
	'VVV-Venlo',
	'Southampton F.C.',
	'Blackburn Rovers F.C.',
	'Sydney FC',
	'Sunderland A.F.C.',
	'Tobago United F.C.',
	'Sevilla Atlético',
	'Atlético Madrid B',
	'Atlético Madrid',
	'Real Zaragoza',
	'Getafe CF',
	'Xerez CD',
	'Córdoba CF',
	'Standard de Liège',
	'Fenerbahçe S.K. (football)',
	'Norwich City F.C.',
	'SC Tavriya Simferopol',
	'Naftovyk Okhtyrka',
	'PFC Sumy',
	'Karpaty Lviv',
	'Dnipro Dnipropetrovsk',
	'FC Karpaty-2 Lviv',
	'FC CSKA Kyiv',
	'Arsenal F.C.',
	'Notts County F.C.',
	'A.F.C. Bournemouth',
	'Brentford F.C.',
	'Wycombe Wanderers F.C.',
	'Seattle Sounders FC U-23',
	'Seattle Sounders FC',
	'Stade Lavallois',
	'Le Mans FC',
	'S.L. Benfica',
	'Granada CF',
	'Udinese Calcio',
	'Al-Fujairah SC',
	'C.F. Os Belenenses',
	'Swindon Town F.C.',
	'Colchester United F.C.',
	'Sheffield United F.C.',
	'Oldham Athletic A.F.C.',
	'Blackpool F.C.',
	'Tranmere Rovers F.C.',
	'Scarborough F.C.',
	'Halifax Town A.F.C.',
	'Morecambe F.C.',
	'Caernarfon Town F.C.',
	'Montpellier HSC',
	'Newcastle United F.C.',
	'A.S. Roma',
	'Olympique Lyonnais',
	'Tampa Bay Mutiny',
	'Julius Berger F.C.',
	'Gil Vicente F.C.',
	'Hapoel Kfar Saba',
	'Portsmouth F.C',
	'Leicester City F. C.',
	'Guangzhou R&F F.C.',
	'Al Rayyan SC',
	'Reading F.C.',
	'Kayserispor',
	'West Bromwich Albion',
	'Racing Club de Avellaneda',
	'Deportivo de La Coruña B',
	'Deportivo de La Coruña',
	'UD Vecindario',
	'C.F. Estrela da Amadora',
	'AS Bari',
	'Real Oviedo',
	'Galatasaray S.K. (football team)',
	'Hannover 96',
	'Los Angeles Galaxy',
	'Plymouth Argyle F.C.',
	'Barnsley F.C.',
	'Walsall F.C.',
	'Darlington F.C.',
	'Aberdeen F.C.',
	'Grimsby Town F.C.',
	'Kidderminster Harriers F.C.',
	'Luton Town F.C.',
	'Forest Green Rovers F.C.',
	'Tamworth F.C.',
	'Harrogate Town F.C.',
	'Corby Town F.C.',
	'Leeds United A.F.C.',
	'St Johnstone F.C.',
	'Livingston F.C.',
	'Linfield F.C.',
	'Nottingham Forest F.C.',
	'Wrexham A.F.C.',
	'Bolton Wanderers F.C.',
	'Crewe Alexandra F.C.',
	'Stoke City F.C.',
	'Hartlepool United F.C.',
	'Aberystwyth Town F.C.',
	'Preston North End F.C.',
	'Oxford United F.C.',
	'Millwall F.C.',
	'Croydon Athletic F.C.',
	'Lewes F.C',
	'Burnley F.C.',
	'Gillingham F.C.',
	'Cheltenham Town F.C.',
	'Fleetwood Town F.C.',
	'AS Monaco FC',
	'En Avant Guingamp',
	'FC Den Bosch',
	'Al-Hilal FC',
	'St Mirren F.C.',
	'Persepolis F.C.',
	'Bishop\'s Stortford F.C.',
	'Buckingham Town F.C.',
	'Perseman Manokwari',
	'Ballymena United F.C.',
	'Leeds United F.C.',
	'AFC Ajax',
	'RBC Roosendaal',
	'S.C. Braga',
	'Anorthosis Famagusta F.C.',
	'Panathinaikos F.C.',
	'Sivasspor',
	'AEK Larnaca',
	'Chester City F.C.',
	'Stockport County F.C.',
	'Bury F.C.',
	'Rotherham United F.C.',
	'Yeovil Town F.C.',
	'Ross County F.C.',
	'Shrewsbury Town F.C.',
	'Rangers F.C.',
	'Colorado Rapids',
	'Southend United F.C.',
	'Peterborough United F.C.',
	'Rushden & Diamonds F.C.',
	'Mansfield Town F.C.',
	'Sheffield F.C.',
	'Eastwood Town F.C.',
	'Real Madrid C.F.',
	'F.C. Internazionale Milano',
	'SV Werder Bremen',
	'Stade Rennais F.C.',
	'Olympique Lyon',
	'FC Metz',
	'FC Nantes',
	'Swansea City A.F.C.',
	'Heart of Midlothian F.C.',
	'Coventry City',
	'NAC Breda',
	'De Graafschap',
	'Leyton Orient F.C.',
	'FC Shakhtar Donetsk',
	'Milton Keynes Dons F.C.',
	'Cradley Town F.C.',
	'Exeter City F.C.',
	'York City F.C.',
	'PEC Zwolle',
	'FC Twente',
	'Grasshopper Club Zürich',
	'FC Terek Grozny',
	'Partick Thistle F.C.',
	'Paris Saint-Germain F.C.',
	'Hibernian F.C.',
	'Mjällby AIF',
	'R.S.C. Anderlecht',
	'LA Galaxy',
	'Newcastle United',
	'Macclesfield Town F.C.',
	'Salisbury City F.C.',
	'New York Express',
	'Los Angeles Lazers',
	'Detroit Neon',
	'Detroit Safari',
	'Raleigh Express',
	'Harlow Town F.C.',
	'HyPS',
	'Seiko SA',
	'Halmstads BK',
	'Waterlooville F.C.',
	'Wycombe Wanderers',
	'Newport (IOW) F.C.',
	'Witton Albion F.C.',
	'Woodley Sports F.C.',
	'Northwich Victoria F.C.',
	'Droylsden F.C.',
	'Huddersfield Town A.F.C.',
	'Mangotsfield United F.C.',
	'Cwmbran Town F.C.',
	'Arnold Kingswell F.C.',
	'Boston United F.C.',
	'Naxxar Lions F.C.',
	'Ilkeston Town F.C. (1945)',
	'Shrewsbury Town F.C ',
	'Home Farm F.C.',
	'Dunfermline Athletic F.C.',
	'Altrincham F.C.',
	'Manchester City',
	'Oldham Athletic',
	'Carlisle United',
	'Sheffield Wednesday',
	'Nantwich Town F.C.',
	'Kettering Town F.C.',
	'Viking FK',
	'Dundee F.C.',
	'Knattspyrnufélag Reykjavíkur',
	'Sabah FA',
	'AFC Wimbledon',
	'Sutton United F.C.',
	'Vitesse Arnhem',
	'Real Sociedad',
	'UD Almería',
	'Sparta Rotterdam',
	'A.C. Monza Brianza 1912',
	'Ajax Cape Town F.C.',
	'Sharks F.C.',
	'Enugu Rangers',
	'1. FC Kaiserslautern',
	'FK Partizan',
	'Al-Arabi SC (Qatar)',
	'Paykan F.C.',
	'Bayern Munich II',
	'VfL Osnabrück',
	'FC Basel',
	'Odense Boldklub',
	'Delfino Pescara 1936',
	'Olympiacos F.C.',
	'Lekhwiya SC',
	'Al-Gharafa Sports Club',
	'Tampa Bay Rowdies (1975–1993)',
	'Arcadia Shepherds F.C.',
	'Tacoma Stars (MISL)',
	'D.C. United',
	'St. Albans City F.C.',
	'Arbroath F.C.',
	'Accrington Stanley F.C.',
	'Salford City F.C.',
	'Double Flower FA',
	'Aldershot Town F.C.',
	'Northern Spirit F.C.',
	'Banstead Athletic F.C.',
	'Croydon F.C.',
	'Bromley F.C.',
	'Inverness Caledonian Thistle F.C.',
	'Maidstone United F.C.',
	'Hemel Hempstead Town F.C.',
	'Leatherhead F.C.',
	'Hastings United F.C.',
	'Chesham United F.C.',
	'Barnet F.C.',
	'Farnborough Town F.C.',
	'Hutnik Nowa Huta',
	'Śląsk Wrocław',
	'Wisła Płock',
	'Amica Wronki',
	'Lech Poznań',
	'Górnik Wałbrzych',
	'Górnik Zabrze',
	'Pecsi Mecsek FC',
	'Budapest Honvéd',
	'Wellington Phoenix FC',
	'Floriana F.C.',
	'Bohemian F.C.',
	'Ayr United F.C.',
	'Valur',
	'Leigh Genesis F.C.',
	'FC Utrecht',
	'Beerschot AC',
	'C.S. Herediano',
	'Málaga CF',
	'Al-Gharafa Doha',
	'Rosario Central',
	'F.C. Tokyo',
	'Chicago Fire S.C.',
	'Airdrieonians F.C. (1878)',
	'Ashton United F.C.',
	'Burton Albion F.C.',
	'Solihull Moors F.C.',
	'Beer Albion FC',
	'Cobham F.C.',
	'Epsom & Ewell F.C.',
	'Eastern AA',
	'Leixões S.C.',
	'Boavista F.C.',
	'F.C. Maia',
	'Gateshead F.C.',
	'Bengaluru FC',
	'U.C. Sampdoria',
	'FC Vysočina Jihlava',
	'FC Baník Ostrava',
	'Club Brugge K.V.',
	'FK Proleter Zrenjanin',
	'FC Moscow',
	'Veria F.C.',
	'FC Saturn Ramenskoye',
	'Sporting Clube de Portugal',
	'FC Karpaty Lviv',
	'FK Vojvodina',
	'Levadiakos F.C.',
	'Enosis Neon Paralimni FC',
	'G.D. Chaves',
	'NK Domžale',
	'Telstar (football club)',
	'1. FSV Mainz 05',
	'Hertha BSC',
	'Fortuna Düsseldorf',
	'AZ (football club)',
	'FC Dordrecht',
	'MVV Maastricht',
	'Real Betis',
	'AZ Alkmaar',
	'Quilmes Atlético Club',
	'Boca Juniors',
	'AC Lugano',
	'Celta de Vigo',
	'FC Internazionale Milano',
	'Club Atlético River Plate',
	'Deportes La Serena',
	'Audax Italiano',
	'Al Shabab (Dubai)',
	'Club Deportivo Universidad Católica',
	'Club Atlético Huracán',
	'A. M. S. y D. Atlético de Rafaela',
	'Club Atlas',
	'Estudiantes Tecos',
	'Derby County FC',
	'Cruz Azul',
	'Pumas UNAM',
	'Tigres UANL',
	'Querétaro FC',
	'SC Bastia',
	'Atromitos F.C.',
	'AS Béziers (2007)',
	'AS Cannes',
	'Juventus F.C.',
	'Melbourne Knights',
	'Dinamo Zagreb',
	'FC Spartak Moscow',
	'Club Olimpia',
	'Hellas Verona',
	'FC Porto',
	'FC Lausanne-Sport',
	'Genoa C.F.C.',
	'FC Zürich',
	'RSC Anderlecht',
	'Standard Liège',
	'Hamburger SV',
	'AS Monaco',
	'Toulouse FC',
	'Blackburn Rovers',
	'Villarreal CF',
	'San Lorenzo de Almagro',
	'Arsenal de Sarandí',
	'FC Energie Cottbus',
	'FC Red Bull Salzburg',
	'Piacenza Calcio',
	'Panathinaikos FC',
	'P.A.O.K.',
	'VfL Wolfsburg',
	'Sport Club Internacional',
	'Associação Académica de Coimbra – O.A.F.',
	'F.C. Tirsense',
	'F.C. Alverca',
	'Vissel Kobe',
	'C.D. Olimpia',
	'Fort Lauderdale Strikers',
	'Crewe Alexandra',
	'Fimleikafélag Hafnarfjarðar',
	'Stade de Reims',
	'IFK Hässleholm',
	'London APSA F.C.',
	'Carshalton Athletic F.C.',
	'Billericay Town F.C.',
	'Grenoble Foot 38',
	'Lille OSC',
	'Oghab F.C.',
	'F.C. Aboomoslem',
	'Tractor Sazi F.C.',
	'Esteghlal Tehran FC',
	'Al Kharaitiyat SC',
	'Esteghlal F.C.',
	'Umm Salal SC',
	'Saipa F.C.',
	'Machine Sazi F.C.',
	'Rosenborg BK',
	'Ørland BK',
	'FC Lyn Oslo',
	'Molde FK',
	'Hapoel Tel Aviv F.C.',
	'Rayo Vallecano',
	'FC Dynamo Kyiv',
	'FC Haka',
	'S.S.D. Licata 1931',
	'S.S.C. Venezia',
	'Reggina Calcio',
	'Ascoli Calcio 1898',
	'FC Groningen',
	'Clermont Foot',
	'Birmingham City',
	'Aldershot F.C.',
	'Waltham Forest F.C.',
	'Perugia Calcio',
	'OFK Belgrade',
	'Havant & Waterlooville',
	'Dundalk F.C.',
	'FK Željezničar Sarajevo',
	'NK Croatia Zagreb',
	'Sporting de Gijón',
	'Paris Saint-Germain',
	'FC Zwolle',
	'Valenciennes FC',
	'Le Havre AC',
	'Le Mans Football Club',
	'Empoli F.C.',
	'Portsmouth FC',
	'Fenerbahçe S.K. (football team)',
	'FC Lorient',
	'Arminia Bielefeld',
	'Willem II (football club)',
	'Hapoel Be\'er Sheva F.C.',
	'Bologna FC',
	'AC ChievoVerona',
	'K.A.A. Gent',
	'A.C. Perugia',
	'KSC Lokeren',
	'Germinal Beerschot',
	'Austria Wien',
	'Rubin Kazan',
	'S.V. Zulte Waregem',
	'Club Brugge',
	'N.E.C. (football club)',
	'Olympiakos F.C.',
	'Boavista Sport Club',
	'Schalke 04',
	'Barnsley FC',
	'VfL Bochum',
	'FC Dnipro Dnipropetrovsk',
	'Leeds United A.F.C',
	'Derby County',
	'Watford FC',
	'Southampton FC',
	'Fluminense FC',
	'Toulouse F.C.',
	'Stade Rennais FC',
	'N.E.C. Nijmegen',
	'Athletic Bilbao',
	'S.E.F. Torres 1903'];


module.exports = pages;